### ISSUE TITLE
Enrollment: Semester & Filter Form

### ISSUE THREAD

**Issue by vanpyrzericj** [vanpyrzericj/Alphon#39]
- Enroll Semester Drop-down wired to db 
- Courses Need Department Code as Separate Property
- Course Offering Needs Capacity Property
- Filter Form (within a semester) POSTs data to action method
-- Department Code Drop-down w/ search (select2)
-- Add Course Number Field (w/ range option)
-- Add Days of the Week checkboxes

**Comment by jf-ub** [comment]
Solved by #46
