### ISSUE TITLE
Finish Cart Header Component

### ISSUE THREAD

**Issue by vanpyrzericj** [vanpyrzericj/Alphon#82]
A branch cart-header has already been started which returns information from the database regarding courses the authenticated user has in their shopping cart. 

From within **WebApp/Features/Student/Shared/Components/TopHeader/Default.cshtml**, add a foreach razor tag to loop through and print out the required data. 

For an example on how this works, check out **WebApp/Features/Student/Dashboard/Dashboard.cshtml** on lines 94-126.

**Comment by jf-ub** [comment]
Solved by #116
